### ISSUE TITLE
error compicc

### ISSUE THREAD

**Issue by Eignar17** [compiz-reloaded/compicc#1] opened 2017-09-18 01:12 UTC
[compiz_crash-7732.txt](https://github.com/compiz-reloaded/compicc/files/1309528/compiz_crash-7732.txt)

**Comment by soreau** [comment] 2017-09-18 01:28
It appears to be crashing in liboyranos used by compicc plugin. Closing this issue since liboyranos is not part of the compiz-reloaded suite.

**Closed by soreau** 2017-09-18 01:28 UTC

**Comment by ethus3h** [comment] 2017-09-18 02:23
(I think this might be a regression in Oyranos, it used to work for me.)
